### ISSUE TITLE
Index out of bounds

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/demo-digit-recognizer#1]
Testing out the algo (@mathias-brandewinder - your updated version) I get: -

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at FSI_0004.compute@96.Invoke(Int32 acc, Int32 i)
   at FSI_0004.predict@104.Invoke(Int32[] img)
   at FSI_0013.createSubmission@132-20.Invoke(Example[] _arg7)
```

When doing a submission across the first 100 items. Have you seen this?

**Comment by mathias-brandewinder** [comment]
Odd - just tried it, and don't get that issue.

**Comment by eiriktsarpalis** [comment]
I had that same issue when I tried to parse test.csv using logic for train.csv. Train has one extra column. Could that be the reason?

**Comment by isaacabraham** [comment]
Will try. I wouldn't put it past me doing something like that.
